### PR TITLE
[r] fix errors when using dx.Explainer

### LINKED ISSUE #318: R package doesn't work with Python Explainer
Beware, `DALEX` doesn't work with `dalex._explainer.object.Explainer` class object.
image

### LINKED ISSUE #319: model_diagnostics returns error when y_hat is of array class
We could potentialy make `model_diagnostics()` more robust to different `y_hat` class.
https://github.com/ModelOriented/DALEX/blob/369a092ce888e71ed0722192933f0bfc0258dd06/R/model_diagnostics.R#L60-L64

image

### PR DESCRIPTION
**Pull request by hbaniecki**
fixes #319 fixes #318

### CODE REVIEW

File: R/misc.R [hunk 1]
```diff
@@ -38,7 +38,7 @@ test_explainer <- function(explainer,
                            has_y = FALSE,
                            function_name = "variable_profile") {
   # run checks against the explainer objects
-  if (!("explainer" %in% class(explainer)))
+  if (!("explainer" %in% class(explainer)) && !("dalex._explainer.object.Explainer" %in% class(explainer)))
```
Comment (pbiecek) [inline R/misc.R:41]: @hbaniecki do we need this in the R code?

**Comment by pbiecek** [comment]
Thanks
